version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000" # Liaison explicite pour Symfony
    expose:
      - "9000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinephoria
      MYSQL_USER: cinephoria
      MYSQL_PASSWORD: cinephoria
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db-data:
