

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinephoria
      MYSQL_USER: cinephoria
      MYSQL_PASSWORD: cinephoria
    networks:
      - cinephoria_network
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    networks:
      - cinephoria_network
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - cinephoria_network
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    networks:
      - cinephoria_network
    ports:
      - "8000:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

networks:
  cinephoria_network:
    driver: bridge

volumes:
  db-data:

