

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinephoria
      MYSQL_USER: cinephoria
      MYSQL_PASSWORD: cinephoria
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    container_name: symfony-backend
    environment:
      DATABASE_URL: "mysql://cinephoria:cinephoria@mysql-db:3306/cinephoria?serverVersion=8.0.31&charset=utf8mb4"
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
  

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  


volumes:
  mysql-data:

