lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'votre_phrase_secrète'  # Utilisée pour protéger la clé privée
    token_ttl: 3600  # Temps d'expiration du token (en secondes)
