framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%' # Transport Doctrine
        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
