nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3001']  # Autoriser uniquement le frontend React
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':  # Applique les règles CORS uniquement pour les routes commençant par /api
            allow_origin: ['*']  # Permet à toutes les origines d'accéder à l'API

